---
- name: Install MAAS
  hosts: localhost
  become: yes

  vars_files:
    - vars/maas_config.yml

  tasks:

    - name: Install required packages
      apt:
        name:
          - snapd
          - postgresql
          - postgresql-contrib
        state: present
        update_cache: yes

    - name: Ensure snapd is running
      systemd:
        name: snapd
        enabled: yes
        state: started

    - name: Disable conflicting NTP (systemd-timesyncd)
      systemd:
        name: systemd-timesyncd
        enabled: no
        state: stopped

    - name: Install MAAS snap
      snap:
        name: maas
        classic: yes
        channel: "{{ maas_snap_channel }}"

    - name: Ensure PostgreSQL is running
      systemd:
        name: postgresql
        enabled: yes
        state: started

    - name: Create PostgreSQL user for MAAS
      become_user: postgres
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        encrypted: yes
        state: present

    - name: Create PostgreSQL database for MAAS
      become_user: postgres
      postgresql_db:
        name: "{{ postgres_database }}"
        owner: "{{ postgres_user }}"
        state: present

    - name: Configure PostgreSQL authentication
      lineinfile:
        path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
        line: "host    {{ postgres_database }}    {{ postgres_user }}    0/0     md5"
        insertbefore: "^# IPv4 local connections:"
        backup: yes
      notify: restart postgresql

    - name: Restart PostgreSQL to apply configuration
      systemd:
        name: postgresql
        state: restarted

    - name: Wait for PostgreSQL to be ready
      wait_for:
        port: 5432
        timeout: 30

    - name: Initialize MAAS with PostgreSQL (production setup)
      shell: |
        sudo maas init region+rack --database-uri "postgres://{{ postgres_user }}:{{ postgres_password }}@{{ postgres_host }}/{{ postgres_database }}" --maas-url "http://{{ ansible_default_ipv4.address | default('localhost') }}:5240/MAAS"
      args:
        creates: /var/snap/maas/common/maas/regiond.conf

    - name: Create MAAS admin user
      shell: |
        sudo maas createadmin --username "{{ maas_admin_user }}" --password "{{ maas_admin_pass }}" --email "{{ maas_admin_email }}"
      args:
        creates: /var/snap/maas/common/maas/.admin-created
      register: admin_creation

    - name: Mark admin user as created
      file:
        path: /var/snap/maas/common/maas/.admin-created
        state: touch
      when: admin_creation.changed

    - name: Wait for MAAS web interface to be available
      wait_for:
        port: 5240
        host: "{{ ansible_default_ipv4.address | default('127.0.0.1') }}"
        timeout: 120

    - name: Show MAAS Web URL
      debug:
        msg:
          - "MAAS production installation completed successfully!"
          - "Access MAAS Web UI at: http://{{ ansible_default_ipv4.address | default(inventory_hostname) }}:5240/MAAS/"
          - "Admin Username: {{ maas_admin_user }}"
          - "Database: PostgreSQL ({{ postgres_database }})"
          - ""
          - "Next steps:"
          - "1. Configure DNS forwarder (e.g., 8.8.8.8)"
          - "2. Import Ubuntu LTS images"
          - "3. Add SSH keys (Launchpad, GitHub, or upload)"
          - "4. Enable DHCP on subnets"

  handlers:
    - name: restart postgresql
      systemd:
        name: postgresql
        state: restarted
