---
- name: Install MAAS
  hosts: maas_servers
  become: yes

  vars_files:
    - vars/maas_config.yml

  tasks:

    - name: Install required packages
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - snapd
        update_cache: yes

    - name: Ensure snapd is running
      systemd:
        name: snapd
        enabled: yes
        state: started

    - name: Install MAAS snap
      snap:
        name: maas
        classic: yes
        channel: "{{ maas_snap_channel }}"

    - name: Wait for MAAS snap to be ready
      wait_for:
        timeout: 30
      delegate_to: localhost

    - name: Ensure PostgreSQL is running
      systemd:
        name: postgresql
        enabled: yes
        state: started

    - name: Wait for PostgreSQL to be ready
      wait_for:
        port: 5432
        host: localhost
        timeout: 60

    - name: Create PostgreSQL user for MAAS
      shell: |
        sudo -u postgres psql -c "SELECT 1 FROM pg_roles WHERE rolname='{{ postgres_user }}'" | grep -q 1 || \
        sudo -u postgres psql -c "CREATE USER \"{{ postgres_user }}\" WITH ENCRYPTED PASSWORD '{{ postgres_password }}'"

    - name: Create PostgreSQL database for MAAS
      shell: |
        sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw {{ postgres_database }} || \
        sudo -u postgres createdb -O "{{ postgres_user }}" "{{ postgres_database }}"

    - name: Initialize MAAS with PostgreSQL
      shell: |
        sudo maas init region+rack --database-uri "postgres://{{ postgres_user }}:{{ postgres_password }}@{{ postgres_host }}/{{ postgres_database }}"

    - name: Create MAAS admin user
      shell: |
        sudo maas apikey --username "{{ maas_admin_user }}" > /dev/null 2>&1 || \
        sudo maas createadmin --username "{{ maas_admin_user }}" --password "{{ maas_admin_pass }}" --email "{{ maas_admin_email }}"